<?php
/**
 *
 * Football [Deutsch — Du]
 *
 * @package language
 * @version $Id: help_football.php 12 2011-03-13 08:03:31Z football $ 
 * @copyright (c) 2010 football (http://football.bplaced.net)
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 *
 *
 */

/**
 * DO NOT CHANGE
 */
if (!defined('IN_PHPBB')) {
	exit;
}

if (empty($lang) || !is_array($lang)) {
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine
//
// Some characters you may want to copy&paste:
// ’ » „ “ — …
//

$lang = array_merge($lang, array(
'FOOTBALL_HELP_FAQ' => array(
array(
0                              => '--',
1                              => 'First steps'
),
array(
0                              => 'How do I install a league?',
1                              => 'When you install this Extension any fixtures are included. Fixture lists can be loaded by "update fixture lists" into the database.
                                   For details, see under this heading.
                                   After installing a fixture list, the settings of the league should be processed and the delivery dates of the match days checked and adjusted if necessary. 
                                   Select manage league to put single users or group members to the prediction league. '
),
array(
0                              => 'Other settings?',
1                              => 'For handle the prediction league(s) you should review and assigned administrative privileges to the members. For automatic sending of 
                                   reminder emails you can set up an external Cornjob. Look that up in the various elements of this help.'
),
array(
0                              => '--',
1                              => 'General'
),
array(
0                              => 'Which prediction leagues are supported?',
1                              => 'All prediction leagues on a championship or KO Round aim. So, soccer leagues, cup competitions, Champions League, Champions League, 
                                   European Championship or World Cup. Even a mix of different competitions is supported, to this table and the statistics show, however, nothing meaningful. 
                                   Only through the point mode Handball is the Extension and other leagues are not suitable for. '
),
array(
0                              => 'What rights exist in the Extension ',
1                              => 'a_football_results = Can enter, modify and delete final game results <br />
                                   a_football_editbets = Can See in the admin area to enter all the tips, and change it<br />
                                   a_football_plan = Unable to create change game plans. Schedule and manage delete (without) and knockout rounds to determine winners<br />
                                   a_football_delete = Can Fixtures and delete parts of it. Delete permission in the schedule management <br />
                                   a_football_config = Can change prediction league settings: prediction league configuration<br />
                                   a_football_points = Can set, change and delete points for Ultimate Points<br />
                                   u_use_football = Can use Prediction League.'
),
array(
0                              => 'What roles exist in this Extension? ',
1                              => 'The football Administrator has just the right match results enter final, otherwise no admin rights. '
),
array(
0                              => 'Which rights were roles assigned to existing ones? ',
1                              => 'The default administrator can enter final Scores, change and delete them. 
                                   The Global Administrator has all the rights of MODS. '
),
array(
0                              => 'Which custom profile fields have been generated by the Extension? ',
1                              => 'footb_email = additional second email address for email alerts<br /> 
                                   footb_rem_f = switch for sending the reminder email to the primary e-mail address.<br />
                                   footb_rem_s = switch for sending the reminder email to the second E-mail address. '
),
array(
0                              => 'How do I activate the reminder e-mail function? ',
1                              => 'In the admin area in the Prediction League functionality the mail reminder cron job and the next run must be activated. <br />
                                   The cron job is run on the first access after this date and sends an e-mail reminder for the missing tip duties that lie in the period 24-48 hours after cron date .
                                   If not sufficient accesses the page, the cron job should automatically run on script "YOUR_URL/cron.php?cron_type=football.football.cron.task.football_remember". <br />
                                   The ship of the email takes place only once . After calling up the cron job, the next scheduled is automatically planned for the following day .
                                   With the appended parameters " & mode = test & days = n " can be tested the shipment for the offset to n days predictions . Only mails to board email address will be shipped .
                                   In ACP a user defined prediction leagues code is to define.<br />
                                   This code XXX must be a cronjob as www.cronjob.de by calling the script "/ football / cron_remember.php? Code = XXX" start.<br />
                                   The call must be at least 24 hours and maximum 33 hours before the final matchday of the place. When multiple calls during the period reminder email will 
                                   be sent again. 
                                   Is the Tip levy as of Friday 20:00 clock must call on Thursday between Thu 11 and 20 clock made.<br />
                                   If the cron job running daily at 13:00 clock, all the deadlines on the following day zwischen 13:00 und 22 clock and no one considered twice. '
),
array(
0                              => 'Who gets a reminder ',
1                              => 'If enabled, reminder function get all the tipsters who play a match with status 0 not fully tapped have to hand 
                                   in on a reminder to the shared (n) e-mail address (es).<br /> 
                                   In addition, an e-mail with the recipient list to the Board e-mail sent (but only if at least one reminder was sent).<br />
                                   The documentation process is logged to the log. '
),
array(
0                              => '--',
1                              => 'Tip Deadline '
),
array(
0                              => 'Tip When the tax is suspended? ',
1                              => 'As soon as someone Data from the prediction leagues will retrieve checks that match status 0 and expired tax time exist with. The to closing 
                                   matches will state 1 and suspend for bet. '
),
array(
0                              => 'The match or matches are not delivery date closed to ',
1                              => 'The tax date is the current host time + time difference between board and host time zone compared. If your host in the set board zone is 
                                   located, it must be time zone in the prediction leagues settings also deposited be. '
),
array(
0                              => 'I can a matchday not edit the submission date ',
1                              => 'You have the league settings "tip submit on each game start" is selected with. This automatically submitting time based games managed. the if 
                                   you remember the game plan preparation, are in should "tip tax until their game starts" only after recognition of the entire game board set is. Then, the 
                                   delivery time is automatically corrected. '
),
array(
0                              => 'The game has already begun, but I can not type yet ',
1                              => 'The match was not yet closed, since the charge time or in the future, and the first game but has already started. Saving the charge time in 
                                   the match day is currently the Time synchronized with the seasons and not reviewed. '
),
array(
0                              => 'checks to save the match day settings ',
1                              => 'When saving a match day, the system checks whether the status of the game day must be corrected. If the 1 . release date in the future, 
                                   the status of the match day 0 set to, he is in the past, 3 the status depending on the status of its games to 1, 2 or Set. '
),
array(
0                              => 'How do I make further deadlines in a game day one? ',
1                              => 'This is only possible if "tip tax until their game starts" in the league settings to "no". Then, two more deadlines deposited will match the. 
                                   The games to 2 deadline to be closed must schedule manual status -1 set to be on the. For the third Deadline Games is the status of the manually set to -2. '
),
array(
0                              => 'What does tip tax until their game starts',
1                              => 'In this mode, each game for the start of the game, typed up by one. When you close the tip submit a game is determined whether any" open 
                                   "games Matchday exist in the. If so, the charge time of the match day to the next start of the game is set, otherwise it remains on the last game and the 
                                   match began with the congestion gets first Predictions for a fixed time before each game is not currently supported. '
),
array(
0                              => '--',
1                              => 'Operating '
),
array(
0                              => 'How to save final scores? ',
1                              => 'Final scores can only be stored in the admin area. Only the results of the selected matches are saved. '
),
array(
0                              => 'I can not enter final scores ',
1                              => 'On prediction leagues functionalities "enter final scores only after match" final scores could entered only after the match (90 minutes).<br /> 
                                   It is not possibleto enter final scores for matches with status 0. For these matches with status 0, please check delivery time. '
),
array(
0                              => 'I want to save a preliminary results',
1                              => 'Preliminary results can be entered only in the User area. '
),
array(
0                              => 'Why do I get different leagues after calling score page? ',
1                              => 'Calling the page "scores" the league which longest waits for a scores is automatically displayed. '
),
array(
0                              => 'Which stage status is set after saving final scores? ',
1                              => 'After saving final scores, the stage status according to the matches is set. 
                                   When all the matches have a status greater than 2, the stage status 3 is set up. Otherwise, stage status ist set to the minimum match status> = 0. '
),
array(
0                              => 'When rankings are updated?',
1                              => 'After saving final or preliminary scores in the user or admin area, the stage ranking is updated. Then, the 
                                   overall ranking is calculated and the places are stored in stage data. The remaining data in the overall ranking are not stored, they are currently calculated. <br />
                                   For stage status 0 or 1, the ranking will be deleted for this stage. The ranking status is set identical to stage status. '
),
array(
0                              => 'How do I delete final scores? ',
1                              => 'Clear final score field(s) or choose delete option and final score ist deleted for this match. The match state will be set to 1. '
),
array(
0                              => 'How do I get games from rating? ',
1                              => 'Set switch "without rating" before saving the match.  no one will receive points for that match. If there is 
                                   no result yet, the game will be saved with state 4, preliminary scores will be state 5, final scores without rating will be state 6. '
),
array(
0                              => 'Who can see all tips?',
1                              => 'User with admin rights a_football_editbets = "Can the admin section view, enter all tips and change" can see and edit all tips of all users in the admin area. '
),
array(
0                              => 'What is Tip entry in the admin area to observe the case?',
1                              => 'Will to games already available results stored Tips is ranked does not automatically update the. The rankings take into account new tip not. 
                                   The display the individual tips and "All Reviews" will be amended tips and the resulting points displayed. If the modified tips rankings included are the in, 
                                   match the results of the match day and the subsequent store again, the rankings newly calculated that. games must not selected or altered it. '
),
array(
0                              => 'What is "KO-round winners identify"? ',
1                              => 'order for the schedule management only teams to choose from in the corresponding round reaches have also must match the team will be registered 
                                   to the team to remain competitive. That, and the transfer to third runners-up teams in the Champions League group stage in the Champions League can be 
                                   performed automatically on this page. As in particular in the calculation of group placement, not all rules were taken into account in the system, 
                                   any errors are corrected manually. This will involve teams of the status message is logged in.
                                   If '
),
array(
0                              => 'How to determine the winner of a knock-out round? ',
1                              => 'For each knockout games, or knock-out rounds with a return game, it is sufficient to match the determination to select where these games have 
                                   taken place as the target game day. Matchday to choose the last to which the team at least competition remains. '
),
array(
0                              => 'How do I determine the group winner and second group ',
1                              => 'In Group Play are all group match to determine select and the last match day round as the target match day to be deposited next to the. The 
                                   "determination on the basis of table space for group games" to choose and the place to which the teams qualify. If teams other league transferred to one in , 
                                   League is the corresponding selected, otherwise not. If no league selected, place and match ignored and not transferred Team. '
),
array(
0                              => 'The teams are already entered in the next round ',
1                              => 'Have Schedule the formulas W (Winner) or L (Looser) deposited in, is already in the display of the encounter between the winners and losers of 
                                   the formula stored in lot (s) are determined and entered in the schedule. Nevertheless, you should "round KO winner determined "called to be, otherwise when 
                                   you saved the game encounter in the game schedule (in game transfer or other change), the teams to choose from and are not therefore be deleted. <br />
                                   The formula G does not lead to an automatic identification, as currently used in the determination of group placement, not all special rules are included in 
                                   the smallest up. The determination must be in the admin section on "knock-out rounds to determine winners" will be implemented and monitored. '
),
array(
0                              => 'without Tipster Tips still get points ',
1                              => 'You have the league settings stored in that Nichttipper the last of the points to get automatically. '
),
array(
0                              => '--',
1                              => 'Schedule Administration '
),
array(
0                              => 'How do I create a new Schedule? ',
1                              => 'To Schedule creation is each page compulsory for bottom-up work off of. In particular Games is the correct filing of the number of match days 
                                   and observed, so the generation process of schedule creation works in the. It was only after generation of the games in Fixtures can Tipper be included as 
                                   previously to the number of games are missing information. Just schedule the switch "tip tax until their game starts" only after generation of the games in 
                                   the visible. This switch should be made only after the deposit of the participating teams and all game dates Yes set to be to ensure that all deadlines set 
                                   will be able to automatically match the in. '
),
array(
0                              => 'How do I set a new season? ',
1                              => 'Under "Seasons Manage" you create a new season with the year, in the season ends. The season 
                                   2010/2011 at the season 2011 so as to create. On the following page will then set appropriate default values. '
),
array(
0                              => 'How do I set up a new league? ',
1                              => 'Under "leagues manage" you create a new league with an indication of a league point. The league number 
                                   should apply to the seasons the same award and are over league one must run away within the season to be>. The first league so should always be the League 
                                   number one, the second league, the league number two always get. '
),
array(
0                              => 'How do I set up a match that? ',
1                              => 'button to generate. In a new league must match the first the missing when the match day one from the standard ". Matchday" get to name 
                                   different, so the field is the appropriate fill, otherwise not. If a submission date filed, participating teams, this Abgabetemin in the generation of the 
                                   start of the game used as. '
),
array(
0                              => 'How I am in a league team? ',
1                              => 'knockout rounds before the case must necessarily match days are recorded, so the team can be assigned to a match, to which the team will remain 
                                   in the competition. The team ID of a team leagues and should be chosen identical across all seasons over so that the statistics work in historical 
                                   comparisons. 
                                   All gif files in the directory / football / images flags / are selecting a team emblem or a flag to display. The arms should be the size 28px x 28px have. 
                                   It is pointed out, the club crest copyrights are subject to, and not the rights holder used to be allowed the consent without. '
),
array(
0                              => 'How do I create the teams participating in the game schedule? ',
1                              => 'After all match days and men were recorded, the database entries for the participating teams will be generated. was before the match a deadline 
                                   deposited with, this is all the games of the match day as the game begins deposited with. Did not have any team a game pairing deposited in, then in the 
                                   summary instead of the Team name a possibly deposited calculation formula. '
),
array(
0                              => 'Can a game plan gradually build me? ',
1                              => 'Yes, you can use during the season more match in the league to add. This one carries the "Leagues Manage the change in the number of match days, 
                                   and then goes to "match" manage where you can to match messages generate new ones. and then edit. After entering the deadlines and number of games in 
                                   knockout rounds, have the games still be generated schedule in . To do this select new added match from and click on the generation button. The lack of 
                                   games will be generated and also missing empty entry all tipsters in the tip table. '
),
array(
0                              => 'When can a league Tipper take in? ',
1                              => 'games on the schedule Tipper can be added after creating the first place. Only then is the function "Manage Leagues" released. '
),
array(
0                              => 'Can I also delete match? ',
1                              => 'Yes, chosen either match "match Manage" on the "Delete" or the last match by the number of match days in the 
                                   league, and then reduces the "match on" Manage and there is then pressed the button displayed. Deleted is always the match with all the games and all tips. '
),
array(
0                              => 'can not play games or nobles I collect? ',
1                              => 'If you have created a knock-out round, you have the number of games at each match deposit. Only then Button appears to complete the game board 
                                   game board Manage. '
),
array(
0                              => 'What&rsquo;s in a game installation? ',
1                              => 'change a game date is after in "tip-out to each start of the game " back to the status of the game and the match day and there deposited 
                                   deadline adapted to. '
),
array(
0                              => 'What are special tips? ',
1                              => 'special tips are single tips with separate scoring. You can be a to a league season to be defined and / or flow thus either in the scoring at 
                                   or in the overall standings one. Matchday the issue to a special tip can match are stored individually, but it should be clear. '
),
array(
0                              => 'What answer - and profit opportunities are available? ',
1                              => 'on the question type is more in response to the selection of a team in the league, a number or text available. The result is still a number of 
                                   values are in addition, each by " ; be separated. "Thus, with a multiple-answer questions can be deposited Choice. If question type 3 or 4 in question, 
                                   the choice of A: B: C: ... H: be marked with the appear in the typing and Score input automatically corresponding values in a dropdown box. '
),
array(
0                              => 'What a question and answer opportunity question type 1? ',
1                              => 'By type of question one can in response and outcome, only one team from the League team list will be selected. The maximum score is only 
                                   awarded in full compliance, otherwise gives the Tipper 0 points. <br />
                                   Sample question: Who will be the Champion '
),
array(
0                              => 'What a question and answer opportunity type of question 2? ',
1                              => 'type of question 2, the question type 1, but the result in writing (or a more team-IDs separated by ";" separately entered). The maximum score 
                                   is awarded if the answer to the selection team associated ID value from the result of a match. <br />
                                   Sample question: Name a relegated team (ranked 16-18 on the seasons end) '
),
array(
0                              => 'What a question and answer opportunity type of question 3? ',
1                              => 'type of question 3 In response and result only value (text or numbers) are stored one. The maximum score is awarded if the answer agrees with 
                                   the result, otherwise gives the Tipper 0 points. <br />
                                   Sample question: How much red (no yellow-red) cards are given to this match? A = 0 B = 1 C = 2 D = more than 2 '
),
array(
0                              => 'What a question and answer opportunity> type of question 4? ',
1                              => 'type of question 4, In response a number or a text and as a result of more numbers or more texts (but not a combination of numbers and text) 
                                   by ";" to be entered separately. The maximum score is awarded if the number or the text in the response with a value of the outcome of matches. <br />
                                   Sample question: Hannover 96 = B = A rises from the cup gets C = C = is not playing international German champions'
),
array(
0                              => 'What a question and answer opportunity type of question 5?',
1                              => 'If question type 5 can result in response and only one number can be stored. The maximum points will be awarded if the answer to the outcome 
                                   is in accordance with, or receives maximum number of tipsters, the less the absolute difference between the response and result, no negative points. <br />
                                   Sample question: How many goals are in this match? '
),
array(
0                              => 'Which ranking is flowing Special Tip a one?',
1                              => 'If delivery and evaluation Matchday be identical, scoring runs in the match score and a ranking. If the evaluation Matchday chosen different, 
                                   special tip flows in the overall classification and ranking one. '
),
array(
0                              => 'I Can Seasonal Tips Creating while? ',
1                              => 'Yes, but only to match which can still be typed. Stored special tips can be moved even then. However, the status of special tips examined 
                                   separately and corrected, if necessary, as with a shift to a no longer tippbaren match the status of the Special tips will automatically be adjusted not.'
),
array(
0                              => 'When special tip is one of the tip release blocked?',
1                              => 'Special tips will be the first delivery date of a match day for the tip tax agreements with. If we want such a Champion tip on 3.Spieltag make 
                                   up, it sets If the levy on Matchday 3 and evaluation on the final day. '
),
array(
0                              => '--',
1                              => 'prediction leagues configuration '
),
array(
0                              => 'What time zone do I have to tip round set? ',
1                              => 'If the host the same time zone of the forum is, is betting the same time zone as the forum to vote in the. If the host in a different time 
                                   zone, then the time zone of the betting difference to set according to the . This is necessary because of supply and result input of the games system time 
                                   functions are used. '
),
array(
	0                         => 'Why is betting code uses the? ',
	1                         => 'To the memory function via cron_remember.php not outsiders can be misused, is the call of the parameters with the betting deposit code compared 
                                        code. Take for instance the code in the admin area deposited 19032038, so should the cronjob cron_remember.php? code = for the reminder call 19,032,038th '
),
array(
0                              => 'How do I show the rankings in the main view, clearly shape the?',
1                              => 'With the switch "Table Tipper in the overview Rankings", the match day overall list will be limited. If the rank by the not notified of an ad 
                                   to run, so the placement will be added to the rankings below. '
),
array(
0                              => '--',
1                              => 'Account overview / Ultimate Points (UP)'
),
array(
0                              => 'It is necessary of the Ultimate Points Extension?',
1                              => 'No if you liked to indicate a balance, nevertheless, the Tippern of your tip round, you should instal the Ultimate Points Extension. <br/> 
                                   Independent of Ultimate Points Extension league profits are credited to the account in phpBB3 football Extension and the Admin can register applications, payments 
                                   and payment.'
),
array(
0                              => 'What does cause the setting "Ultimate Points integrate" in the prediction league functionalities in the Administration?',
1                              => 'This setting has only consequences on the automatic settlement of the profits in the balance of Ultimate Points. Here one can choose 
                                   whether profits, points or nothing from phpBB3 football Extension should flow in onto the Ultimate Points balance. The settlement of the achieved prediction 
                                   league points can be steered, in addition, still about a factor. '
),
array(
0                              => 'Can see other my account overview?',
1                              => 'Only who owns suitable rights, the account overview of another Tippers can question in the prediction league area.'
),
array(
0                              => 'How are wagers, deposits and payment and profits registered?',
1                              => 'Wagers charge the account and the balance of UP and can be compensated by payments again. In the season credited profits can be paid by the 
		                         account and the payment likewise charge the balance in UP. Profits are registered automatically about the profit distribution of the prediction 
		                         league with the memory of the play results with the account and UP (with sedate counter). With renewed storing away of results the old reservations 
		                         are cancelled and booked anew. Should results already exist in the following matchdays, the matching ranking lists and reservations are corrected.
		                         Deposits and payments-out are only for real payments.'
),
array(
0                              => 'booking wagers',
1                              => 'If UP is installed and is activated with the beech, the wager is drawn off from the balance UP. The wager can be debited a sum to an account 
		                         for a complete league or for single user. With the reservation for the whole league quite booked wagers are already taken into consideration before, 
		                         so that all together at most the wager deposited in the league is debited a sum to an account. With single debit ever well-chosen user the back 
		                         wager are put down as a default on the respective input fields. If these values are changed no examination on under or over charging occurs.'
),
array(
0                              => 'booking deposits',
1                              => 'If UP is installed and is activated with the beech, the deposit is credited to the balance. Therefore resulted negative account balances can 
                                   be compensated by deposits again. Deposits can be booked for a complete league or for single user. With the reservation for the whole league booked 
                                   deposits are already taken into consideration before, so that all together at most the application deposited in the league is booked. With single 
                                   reservation ever well-chosen user the final deposits are put down as a default on the respective input fields. If these values are changed no examination 
                                   on under or over charging occurs.'
),
array(
0                              => 'booking payments',
1                              => 'If UP is installed and is activated with the beech, the payment loads the balance. Therefore achieved profits can be paid in the season and 
                                   the balance be equalised. Payments can be booked for a complete league or for single user. With the reservation for the whole league booked payment is 
                                   already taken into consideration before, so that all together at most the profit get in the league is booked up. With single reservation ever well-chosen 
                                   user the back payment is put down as a default on the respective input fields. If these values are changed no examination on under or over charging occurs.'
),
array(
0                              => 'Approach after the update on version 0.9.2',
1                              => 'With the update phpBB3 football MODs on version 0.9.2 ranking lists are anew calculated (also from the years before) and the profits are 
                                   registered automatically in the account. Besides, a settlement with the UP balance is not carried out. If this is welcome, the 
                                   option  "integrate Ultimate Points" are put accordingly and the match results of the first matchday league once more are stored away. Wagers, 
                                   deposits and payment must be postsettled by hand in the Administration for each season. Before one should decide whether these reservations should be 
                                   also taken into consideration in the UP balance and put accordingly the option for UP.'
),
array(
0                              => '--',
1                              => 'Fixture list Update'
),
array(
0                              => 'How to Schedule Update',
1                              => 'An update on the fixture list can be carried out only with data from another Football Extension site. An overview of the available seasons
                                   and leagues is seen on /football/xml/football_xml_season.php starting from the phpbb root directory. If this complete address entered directly 
                                   in the browser, the XML data will be displayed. After click on a league the current data from the League shown here. If you click in this view on 
                                   disk icon, you can download the data of the league as an XML file.<br />
                                   When you start the update in the admin area under Fixture List update the saved settings for season overview is listed as an update source. If no 
                                   Source is stored, the Football Extension Demo site is registered as a source. After loading the season overview the available leagues are offered for selection. 
                                   If access is not supported on a different URL from your hoster you must take to download from desired leagues as an XML file and store it under root/store.
                                   In this case, save localhost in football settings for future calls.<br />
                                   Access to the season and the league data can be protected by a code. Users of the updates must use the code xxxx when calling the Season overview by 
                                   appending ?code=xxxx. So call /football/xml/football_xml_season.php?code=xxxx. During the subsequent call to the League data the code will be passed.
                                   As target, you can choose an existing league or a league by entering the new league ID. To set up a new league, the target season must exist.
                                   In this case, all data of the update file transferred to database after switching season and league ID.<br />
                                   If an existing league is selected, first season and league-ID will be replaced and the teams compared with the database. For differing Team IDs
                                   or different number of teams is to do in the next step, a team mapping. Then, any deviations between update and database is displayed and you can select 
                                   rows and columns the data to be transferred. Note different defaults for the column selection. After updating the database deadlines and status 
                                   are automatically corrected on matchdays and the the ranking of the league is recalculated.<br />
                                   In the admin log a summary of the changes are logged.'
),
array(
0                              => 'Team Mapping',
1                              => 'The team mapping is necessary if the team IDs are not identical or the number of teams is different. Recently added teams
                                   e.g. in the EL the third of CL, are inserted in the database. After the mapping the program check whether all the existing teams are
                                   assigned. The Team IDs are exchanged on the basis of the mapping in the update data. New teams are added only during the actual update.'
),
array(
0                              => 'Match Status',
1                              => 'When generating the XML data, the status 4-6 will be changed to 1-3, ie in the update, there are no games without evaluation.
                                   For games with game status < 2, the goal Fields and the state itself is not accepted. Is database sttaus larger than 3, this status is maintained 
                                   and the update program treats the data as with the corresponding status 1-3. Prerequisite for data acquisition under consideration of the status, however, 
                                   remains the selection of appropriate columns and records on matches.'
),
array(
0                              => 'Take over negative status',
1                              => 'If this option is set, the negative status, but not the goals will be taken. This enables the staggered deadlines
                                   to take on the update. The deadlines are to take either of the update (column options in matchdays) or manually in the admin area.
                                   In a league with "Bet in time" the option "Take over negative status" can not be selected.'
),
array(
0                              => 'Update results with same status',
1                              => 'Only if this option is set, the goal fields from the update with the same status in update and database will be updated. This
                                   overwrites already recorded (preliminary) results in the database. This also applies to games in the database without evaluation.
                                   Status 3 overwrites the final results with status 6 in the database. Analog overrides status 2 in the update
                                   preliminary results from the classification made by state 4, but only if "Take over only final results" option is not selected.'
),
array(
0                              => 'Take over only final results',
1                              => 'If this option is set, only the goal-fields from the update record must be taken when the status of the match in the update is 3.
                                   Preliminary results from the update are not used. If these should be taken, this option is explicitly set off. '
),
array(
0                              => 'Using the Cache',
1                              => 'The seasons- and the leagues-data are stored for 5 minutes in the cache, so that the data are downloaded from Source only once. If you need 
                                   updated data within that time anyway, you have to delete the cache to force a new download from the Source.'
),)
));
?>